#############
# Sys Clock #
#############

# 100 MHz input clock
set SYS_TCK 10.0
create_clock -period $SYS_TCK -name sys_clk [get_ports sys_clk_i]

# SoC clock is generated by clock wizard and its constraints
set SOC_TCK 50.0
set soc_clk [get_clocks -of_objects [get_pins i_clkwiz/clk_20]]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets jtag_tck_i_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sys_resetn_IBUF]


############
# Switches #
############

set_input_delay -min -clock $soc_clk [expr { $SOC_TCK * 0.10 }] [ \
    get_ports {gpio_i* fan_sw* fetch_en_i}]
set_input_delay -max -clock $soc_clk [expr { $SOC_TCK * 0.35 }] [ \
    get_ports {gpio_i* fan_sw* fetch_en_i}]

set_output_delay -min -clock $soc_clk [expr { $SOC_TCK * 0.10 }] [get_ports fan_pwm]
set_output_delay -max -clock $soc_clk [expr { $SOC_TCK * 0.35 }] [get_ports fan_pwm]

set_max_delay [expr { 2 * $SOC_TCK }] -from [get_ports {gpio_i* fan_sw* fetch_en_i}]
set_false_path -hold -from [get_ports {gpio_i* fan_sw* fetch_en_i}]

# LEDs
set_output_delay -min -clock $soc_clk [expr { $SOC_TCK * 0.10 }] [get_ports gpio_o]
set_output_delay -max -clock $soc_clk [expr { $SOC_TCK * 0.35 }] [get_ports gpio_o]


###############
# Assign Pins #
###############

# tclint-disable line-length, spacing

## Clock Signal
set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports sys_clk_i]

## Reset Button
set_property -dict { PACKAGE_PIN D19   IOSTANDARD LVCMOS33 } [get_ports { sys_reset }];

## Switch and Button
set_property -dict { PACKAGE_PIN D20   IOSTANDARD LVCMOS33 } [get_ports { gpio_i[0] }]; # Buttons
set_property -dict { PACKAGE_PIN L20   IOSTANDARD LVCMOS33 } [get_ports { gpio_i[1] }]; # Buttons
set_property -dict { PACKAGE_PIN L19   IOSTANDARD LVCMOS33 } [get_ports { gpio_i[2] }]; # Buttons
set_property -dict { PACKAGE_PIN M20   IOSTANDARD LVCMOS33 } [get_ports { gpio_i[3] }]; # Switch
set_property -dict { PACKAGE_PIN M19   IOSTANDARD LVCMOS33 } [get_ports { fetch_en_i }]; # Switch

## LEDs
set_property -dict { PACKAGE_PIN R14   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[0] }];
set_property -dict { PACKAGE_PIN P14   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[1] }];
set_property -dict { PACKAGE_PIN N16   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[2] }];
set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[3] }];

##### PMOD JA
## DPTI
# Note: DPTI and DSPI constraints cannot be used in the same design, as they share pins.
# set_property -dict { PACKAGE_PIN Y18   IOSTANDARD LVCMOS33 } [get_ports { jtag_tck_i }];
# set_property -dict { PACKAGE_PIN Y19   IOSTANDARD LVCMOS33 } [get_ports { jtag_tdi_i }];
# set_property -dict { PACKAGE_PIN Y16   IOSTANDARD LVCMOS33 } [get_ports { jtag_tdo_o }];
# set_property -dict { PACKAGE_PIN Y17   IOSTANDARD LVCMOS33 } [get_ports { jtag_tms_i }];

set_property -dict { PACKAGE_PIN Y18   IOSTANDARD LVCMOS33 } [get_ports { jtag_tdo_o }];
set_property -dict { PACKAGE_PIN Y19   IOSTANDARD LVCMOS33 } [get_ports { jtag_tck_i }];
set_property -dict { PACKAGE_PIN Y16   IOSTANDARD LVCMOS33 } [get_ports { jtag_tms_i }];
set_property -dict { PACKAGE_PIN Y17   IOSTANDARD LVCMOS33 } [get_ports { jtag_tdi_i }];

## UART
### PMODA 7 and 8 Consecutively
#set_property -dict { PACKAGE_PIN U18   IOSTANDARD LVCMOS33 } [get_ports { uart_tx_o }];
#set_property -dict { PACKAGE_PIN U19   IOSTANDARD LVCMOS33 } [get_ports { uart_rx_i }];

### PMODB 1 and 2 Consecutively
set_property -dict { PACKAGE_PIN W14   IOSTANDARD LVCMOS33 } [get_ports { uart_tx_o }];
set_property -dict { PACKAGE_PIN Y14   IOSTANDARD LVCMOS33 } [get_ports { uart_rx_i }];
####

# tclint-enable line-length, spacing


