#############
# Sys Clock #
#############

# 125 MHz input clock
set SYS_TCK 8
create_clock -period $SYS_TCK -name sys_clk [get_ports sys_clk_p]

# SoC clock is generated by clock wizard and its constraints
set SOC_TCK 50.0
set soc_clk [get_clocks -of_objects [get_pins i_clkwiz/clk_20]]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets jtag_tck_i_IBUF_inst/O]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sys_reset_IBUF_inst/O]

############
# Switches #
############

set_input_delay -min -clock $soc_clk [expr { $SOC_TCK * 0.10 }] [ \
    get_ports {gpio_i* fan_sw* fetch_en_i}]
set_input_delay -max -clock $soc_clk [expr { $SOC_TCK * 0.35 }] [ \
    get_ports {gpio_i* fan_sw* fetch_en_i}]

set_output_delay -min -clock $soc_clk [expr { $SOC_TCK * 0.10 }] [get_ports fan_pwm]
set_output_delay -max -clock $soc_clk [expr { $SOC_TCK * 0.35 }] [get_ports fan_pwm]

set_max_delay [expr { 2 * $SOC_TCK }] -from [get_ports {gpio_i* fan_sw* fetch_en_i}]
set_false_path -hold -from [get_ports {gpio_i* fan_sw* fetch_en_i}]

# LEDs
set_output_delay -min -clock $soc_clk [expr { $SOC_TCK * 0.10 }] [get_ports gpio_o]
set_output_delay -max -clock $soc_clk [expr { $SOC_TCK * 0.35 }] [get_ports gpio_o]

###############
# Assign Pins #
###############

## Sys clock
set_property -dict {PACKAGE_PIN E23 IOSTANDARD LVDS} [get_ports sys_clk_n]
set_property -dict {PACKAGE_PIN F23 IOSTANDARD LVDS} [get_ports sys_clk_p]

## Reset
set_property -dict {PACKAGE_PIN M11 IOSTANDARD LVCMOS33} [get_ports sys_reset]

## Buttons
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports gpio_i[0]]
set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports gpio_i[1]]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports gpio_i[2]]
set_property -dict {PACKAGE_PIN C3 IOSTANDARD LVCMOS33} [get_ports gpio_i[3]]

## PMOD 0
# set_property -dict {PACKAGE_PIN G8 IOSTANDARD LVCMOS33} [get_ports jtag_tms_i]
# set_property -dict {PACKAGE_PIN H8 IOSTANDARD LVCMOS33} [get_ports jtag_tdi_i]
# set_property -dict {PACKAGE_PIN G7 IOSTANDARD LVCMOS33} [get_ports jtag_tdo_o]
# set_property -dict {PACKAGE_PIN H7 IOSTANDARD LVCMOS33} [get_ports jtag_tms_i]

set_property -dict {PACKAGE_PIN G8 IOSTANDARD LVCMOS33} [get_ports jtag_tdo_o]
set_property -dict {PACKAGE_PIN H8 IOSTANDARD LVCMOS33} [get_ports jtag_tck_i]
set_property -dict {PACKAGE_PIN G7 IOSTANDARD LVCMOS33} [get_ports jtag_tms_i]
set_property -dict {PACKAGE_PIN H7 IOSTANDARD LVCMOS33} [get_ports jtag_tdi_i]

# set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports pad_pmod0_4]
# set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports pad_pmod0_5]
# set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS33} [get_ports pad_pmod0_6]
# set_property -dict {PACKAGE_PIN J7 IOSTANDARD LVCMOS33} [get_ports pad_pmod0_7]

# ## PMOD 1
# set_property -dict {PACKAGE_PIN J9  IOSTANDARD LVCMOS33} [get_ports pad_uart_cts]
# set_property -dict {PACKAGE_PIN K9  IOSTANDARD LVCMOS33} [get_ports pad_uart_rts]
# set_property -dict {PACKAGE_PIN K8  IOSTANDARD LVCMOS33} [get_ports pad_pmod1_2]
# set_property -dict {PACKAGE_PIN L8  IOSTANDARD LVCMOS33} [get_ports pad_pmod1_3]
# set_property -dict {PACKAGE_PIN L10 IOSTANDARD LVCMOS33} [get_ports pad_pmod1_4]
# set_property -dict {PACKAGE_PIN M10 IOSTANDARD LVCMOS33} [get_ports pad_pmod1_5]
# set_property -dict {PACKAGE_PIN M8  IOSTANDARD LVCMOS33} [get_ports pad_pmod1_6]
# set_property -dict {PACKAGE_PIN M9  IOSTANDARD LVCMOS33} [get_ports pad_pmod1_7]

## UART
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS18} [get_ports uart_rx_i]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS18} [get_ports uart_tx_o]
# set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS18} [get_ports led0_o]
# set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS18} [get_ports pad_pmod1_0]

## LEDs
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports gpio_o[0]]
set_property -dict {PACKAGE_PIN D6 IOSTANDARD LVCMOS33} [get_ports gpio_o[1]]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports gpio_o[2]]
set_property -dict {PACKAGE_PIN B5 IOSTANDARD LVCMOS33} [get_ports gpio_o[3]]

## Switches
set_property -dict {PACKAGE_PIN E4 IOSTANDARD LVCMOS33} [get_ports fetch_en_i]
# set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports switch1_i]
# set_property -dict {PACKAGE_PIN F5 IOSTANDARD LVCMOS33} [get_ports switch2_i]
# set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports switch3_i]

# ## I2C Bus
# set_property -dict {PACKAGE_PIN N12 IOSTANDARD LVCMOS33} [get_ports pad_i2c0_scl]
# set_property -dict {PACKAGE_PIN P12 IOSTANDARD LVCMOS33} [get_ports pad_i2c0_sda]

# ## HDMI CTL
# set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVCMOS33} [get_ports pad_hdmi_scl]
# set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports pad_hdmi_sda]
